version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3.9.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # RabbitMQ main port
      - "15672:15672"   # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "montaser"
      RABBITMQ_DEFAULT_PASS: "montaser"
      RABBITMQ_ERLANG_COOKIE: "secret-cookie"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   # Persist RabbitMQ data
    networks:
      - my-network

  app:
    container_name: my_parking_system
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    env_file:
      - ./server/.env 
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  pgdata:
  rabbitmq_data:

networks:
  my-network: 
    driver: bridge