version: "3.9"

services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]
    networks:
      - mongoCluster

  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]
    networks:
      - mongoCluster

  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
    networks:
      - mongoCluster

  mongo-setup:
    image: mongo:5
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongoCluster
    entrypoint: ["sh", "-c"]
    command:
      - |
        sleep 5
        mongosh --host mongo1 --eval '
          rs.initiate({
            _id: "myReplicaSet",
            members: [
              { _id: 0, host: "localhost:27017" },
              { _id: 1, host: "localhost:27018" },
              { _id: 2, host: "localhost:27019" }
            ]
          })'

networks:
  mongoCluster:
    driver: bridge
